In [1]:
import torch

Uninitialized matrix definition.

This is simply to allocate memory space

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[ 1.9567e-30,  4.5608e-41,  1.9567e-30],
        [ 4.5608e-41,  2.1046e-37,  0.0000e+00],
        [ 1.2360e-17,  9.8215e+08,  3.0854e-36],
        [ 6.5488e-39,  1.5322e+10,  1.5301e+10],
        [-1.9637e-34,  4.5607e-41,  0.0000e+00]])


Initialized matrix

It contains values already. In this case it has been created with random values. 

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.2031, 0.5581, 0.5970],
        [0.2600, 0.4077, 0.9853],
        [0.2738, 0.4329, 0.4678],
        [0.2553, 0.4322, 0.0010],
        [0.4617, 0.1177, 0.3047]])


Or initialize it with zeros. 

The class "long" is an integer of large size. In normal python 3, "normal" integers and long have been unified as "int" for simplicity. 

In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Also construc tensors



In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


You can also create tensors based on elements of previous tensors (data, data type, size...)

In [20]:
x = x.new_ones(5,3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.1139,  0.0199,  0.1239],
        [ 0.6418,  0.3218, -0.2047],
        [-0.0370, -1.1786,  0.6601],
        [-0.3338,  0.8745, -0.3865],
        [ 0.8269, -0.7640,  0.2366]])


Find size of tensor

In [21]:
print(x.size())result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

torch.Size([5, 3])


# Operations

## Sum: 2 syntaxes, same result

In [22]:
y = torch.rand(5,3)
print(x+y)

tensor([[ 0.3300,  0.5101,  0.3114],
        [ 1.3009,  1.0314,  0.3325],
        [ 0.3163, -0.3372,  1.3379],
        [ 0.4664,  0.9574, -0.2154],
        [ 1.1998, -0.6304,  0.6031]])


In [23]:
print(torch.add(x, y))

tensor([[ 0.3300,  0.5101,  0.3114],
        [ 1.3009,  1.0314,  0.3325],
        [ 0.3163, -0.3372,  1.3379],
        [ 0.4664,  0.9574, -0.2154],
        [ 1.1998, -0.6304,  0.6031]])


## Specify where the output is stored

In [24]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.3300,  0.5101,  0.3114],
        [ 1.3009,  1.0314,  0.3325],
        [ 0.3163, -0.3372,  1.3379],
        [ 0.4664,  0.9574, -0.2154],
        [ 1.1998, -0.6304,  0.6031]])


## In-place addition

In [25]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 0.3300,  0.5101,  0.3114],
        [ 1.3009,  1.0314,  0.3325],
        [ 0.3163, -0.3372,  1.3379],
        [ 0.4664,  0.9574, -0.2154],
        [ 1.1998, -0.6304,  0.6031]])


Torch is very numpy-like. Eg:

In [27]:
print(x[:, 1])

tensor([ 0.0199,  0.3218, -1.1786,  0.8745, -0.7640])


## Resize

In [29]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [32]:
x

tensor([[ 0.4086,  1.8899, -0.1309,  1.1995],
        [-0.9648,  0.2491, -0.2338, -1.4124],
        [-1.2063, -0.7544, -0.3772, -0.1277],
        [ 0.1331,  0.0901, -0.4816,  1.3189]])

In [31]:
y

tensor([ 0.4086,  1.8899, -0.1309,  1.1995, -0.9648,  0.2491, -0.2338, -1.4124,
        -1.2063, -0.7544, -0.3772, -0.1277,  0.1331,  0.0901, -0.4816,  1.3189])

In [33]:
z

tensor([[ 0.4086,  1.8899, -0.1309,  1.1995, -0.9648,  0.2491, -0.2338, -1.4124],
        [-1.2063, -0.7544, -0.3772, -0.1277,  0.1331,  0.0901, -0.4816,  1.3189]])

If you have a one element tensor, use `.item()` to get the value as a Python number. The stored float is more precise than the displayed one. 

In [34]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.3051])
-0.30511876940727234


# Convert between pytorch and numpy

## Pytorch to Numpy

In [46]:
a = torch.ones(5,2)
print(a)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


In [47]:
b = a.numpy()
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [50]:
a.add_(1)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.]])

In [51]:
b

array([[2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.],
       [2., 2.]], dtype=float32)

Observe how changing the value of a automatically updated b

## Numpy to Pytorch

In [54]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# CUDA Tensors

Tensors can be moved onto any device using the `.to` method.

In [ ]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!