In [1]:
import torch
import numpy as np
import torch.nn as nn
import torch.nn.functional as F

In [2]:
xy = torch.randn(10000,1,2)
z = 10*xy[:,:,0] + np.random.uniform(-0.1,0.1) + 2*xy[:,:,1] +np.random.uniform(-0.1,0.1)
z= z.reshape(-1, 1)
z = np.expand_dims(z, axis = 1)

# train_data = torch.from_numpy(xy)
train_label = torch.from_numpy(z)
print(type(train_label))

<class 'torch.Tensor'>


In [3]:
class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear1 = nn.Linear(2, 5)
        self.linear2 = nn.Linear(5, 3)
        self.linear3 = nn.Linear(3, 1)
        
    def forward(self, x):
        x = F.relu(self.linear1(x))
        x = F.relu(self.linear2(x))
        x = self.linear3(x)
        return(x)
        
net = Net()
print(net)

Net(
  (linear1): Linear(in_features=2, out_features=5, bias=True)
  (linear2): Linear(in_features=5, out_features=3, bias=True)
  (linear3): Linear(in_features=3, out_features=1, bias=True)
)


In [16]:
class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear1 = nn.Linear(2, 1)
        
    def forward(self, x):
        x = self.linear1(x)
        return(x)
        
net = Net()
print(net)

Net(
  (linear1): Linear(in_features=2, out_features=1, bias=True)
)


In [17]:
params = list(net.parameters())
print(params)

[Parameter containing:
tensor([[-0.1355,  0.5856]], requires_grad=True), Parameter containing:
tensor([0.2312], requires_grad=True)]


In [18]:
print(list(net.named_parameters()))

[('linear1.weight', Parameter containing:
tensor([[-0.1355,  0.5856]], requires_grad=True)), ('linear1.bias', Parameter containing:
tensor([0.2312], requires_grad=True))]


In [19]:
inp = torch.rand(100, 1,2)
# print(inp)
# print(inp.size())

In [20]:
out = net(inp)

In [21]:
net.zero_grad()

In [22]:
net.zero_grad()
out.backward(inp)

In [23]:
z[0][0][0]

-6.69869

In [24]:
criterion = nn.MSELoss()# Mean Squared Loss
optimizer = torch.optim.SGD(net.parameters(), lr=0.001, momentum=0.9)

In [25]:
for epoch in range(5):
    running_loss = 0.0  # Reset the loss
    
    for i, data in enumerate(xy):  # Training set
        
        # Reset gradient here, since they are additive
        optimizer.zero_grad()
        
        # Run the net
        outputs = net(data)
        loss = criterion(outputs, torch.tensor(z[i]))
        loss.backward()
        optimizer.step()
        
         # print statistics
        running_loss += loss.item()
        if i % 2000 == 1999:    # print every 2000 mini-batches
            print('[%d, %5d] loss: %.3f' %
                  (epoch + 1, i + 1, running_loss / 2000))
            running_loss = 0.0

print('Finished Training')

[1,  2000] loss: 1.707
[1,  4000] loss: 0.000
[1,  6000] loss: 0.000
[1,  8000] loss: 0.000
[1, 10000] loss: 0.000
[2,  2000] loss: 0.000
[2,  4000] loss: 0.000
[2,  6000] loss: 0.000
[2,  8000] loss: 0.000
[2, 10000] loss: 0.000
[3,  2000] loss: 0.000
[3,  4000] loss: 0.000
[3,  6000] loss: 0.000
[3,  8000] loss: 0.000
[3, 10000] loss: 0.000
[4,  2000] loss: 0.000
[4,  4000] loss: 0.000
[4,  6000] loss: 0.000
[4,  8000] loss: 0.000
[4, 10000] loss: 0.000
[5,  2000] loss: 0.000
[5,  4000] loss: 0.000
[5,  6000] loss: 0.000
[5,  8000] loss: 0.000
[5, 10000] loss: 0.000
Finished Training


In [26]:
print(list(net.named_parameters()))

[('linear1.weight', Parameter containing:
tensor([[10.0000,  2.0000]], requires_grad=True)), ('linear1.bias', Parameter containing:
tensor([-0.0284], requires_grad=True))]
